#%RAML 1.0 Library

usage: This a namespace of common, reusable data types

types: 
  Address: !include types/address-type.raml
  EmailAddress: !include types/emailAddress-type.raml
  ErrorMessage: !include types/errorMessage-type.raml
  PersonName: !include types/personName-type.raml
  Phone: !include types/phone-type.raml
  SourceSystem: !include types/sourceSystem-type.raml
  Gender: !include types/gender-type.raml
  MaritalStatus: !include types/maritalStatus-type.raml
  